export const isAndroid: any
export const isCarNumber: any
export const isChinese: any
export const isColorHex: any
export const isCreditCode: any
export const isDouble: any
export const isEmail: any
export const isHttpLink: any
export const isIdCard: any
export const isImage: any
export const isInteger: any
export const isIos: any
export const isIPad: any
export const isIpv4: any
export const isLetter: any
export const isLowerLetter: any
export const isMobileNumber: any
export const isMoney: any
export const isNumber: any
export const isNumberAndLetter: any
export const isPc: any
export const isPostalCode: any
export const isQQNumber: any
export const isTelephoneNumber: any
export const isUpperLetter: any
export const isWeixin: any
export const isWeixinNumber: any
export const isXml: any
